### ISSUE TITLE
error regarding AttributeError: 'function' object has no attribute '__wrapped__'

### ISSUE THREAD

**Issue by chinobing** [nicolaskruchten/dash_callback_chain#1]
Thanks for your great work!!! I tried to duplicate your demo by using the code below:
```
import dash_callback_chain as chainvis
import dash
from dash.dependencies import Input, Output
import dash_html_components as html
import dash_core_components as dcc

app = dash.Dash('')

app.scripts.config.serve_locally = True

all_options = {
    'America': ['New York City', 'San Francisco', 'Cincinnati'],
    'Canada': [u'Montréal', 'Toronto', 'Ottawa']
}
app.layout = html.Div([
    chainvis.CallbackChainVisualizer(id="chain"),
    html.Hr(),
    dcc.RadioItems(
        id='countries-dropdown',
        options=[{'label': k, 'value': k} for k in all_options.keys()],
        value='America'
    ),

    html.Hr(),

    dcc.RadioItems(id='cities-dropdown'),

    html.Hr(),

    html.Div(id='display-selected-values')
])


@app.callback(
    dash.dependencies.Output('cities-dropdown', 'options'),
    [dash.dependencies.Input('countries-dropdown', 'value')])
def set_cities_options(selected_country):
    return [{'label': i, 'value': i} for i in all_options[selected_country]]


@app.callback(
    dash.dependencies.Output('cities-dropdown', 'value'),
    [dash.dependencies.Input('countries-dropdown', 'value')])
def set_cities_value(selected_country):
    return all_options[selected_country][0]


@app.callback(
    dash.dependencies.Output('display-selected-values', 'children'),
    [dash.dependencies.Input('countries-dropdown', 'value'),
     dash.dependencies.Input('cities-dropdown', 'value')])
def set_display_children(selected_country, selected_city):
    return u'{} is a city in {}'.format(
        selected_city, selected_country,
    )



@app.callback( Output('chain', 'dot'), [Input('chain', 'id')] )
def show_chain(s): 
    return chainvis.dot_chain(app, ["show_chain"])

if __name__ == '__main__':
    app.run_server(debug=True)    
```

But no graph is shown and an error message pops up.
```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1997, i
n __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1985, i
n wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1540, i
n handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\_compat.py", line 33,
 in reraise
    raise value
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1982, i
n wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1614, i
n full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1517, i
n handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\_compat.py", line 33,
 in reraise
    raise value
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1612, i
n full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1598, i
n dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Anaconda3\lib\site-packages\dash\dash.py", line 551, in
 dispatch
    return self.callback_map[target_id]['callback'](*args)
  File "C:\Program Files\Anaconda3\lib\site-packages\dash\dash.py", line 508, in
 add_context
    output_value = func(*args, **kwargs)
  File "C:\Users\Administrator\untitled26.py", line 116, in show_chain
    return chainvis.dot_chain(app, ["show_chain"])
  File "C:\Program Files\Anaconda3\lib\site-packages\dash_callback_chain\__init_
_.py", line 42, in dot_chain
    wrapped_func = callback['callback'].__wrapped__
AttributeError: 'function' object has no attribute '__wrapped__'
127.0.0.1 - - [29/Jun/2018 10:01:00] "POST /_dash-update-component HTTP/1.1" 200
 -
```

**Comment by mungojam** [comment]
@chinobing

Your sample code works perfectly for me. Have you got the latest dash packages?

**Comment by chinobing** [comment]
actually, this plugin worked perfectly to me after a few tries and I forgot to close this issue. I am sorry about that.
