### ISSUE TITLE
Does not handle multiple outputs

### ISSUE THREAD

**Issue by zouhairm** [nicolaskruchten/dash_callback_chain#2]
Dash is going to handle multiple outputs (see https://github.com/plotly/dash/pull/436)

Looks like this nifty tool doesn't handle that yet. I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 1024, in dispatch
    return self.callback_map[output]['callback'](*args)
  File "/usr/local/lib/python3.7/site-packages/dash/dash.py", line 935, in add_context
    output_value = func(*args, **kwargs)
  File "app.py", line 111, in show_chain
    def show_chain(s): return chainvis.dot_chain(app, ["show_chain"])
  File "/usr/local/lib/python3.7/site-packages/dash_callback_chain/__init__.py", line 45, in dot_chain
    output, output_prop = callback_id.split(".")
```

**Comment by nicolaskruchten** [comment]
Hehe well yes, the multiple-outputs stuff is unreleased, so this tool hasn't been updated quite yet! :P

**Comment by zouhairm** [comment]
@nicolaskruchten : great to hear it's on your radar. I think the release should be coming soon as it's part of 0.38rc and Dash is at 0.37

Let me know if you need a beta tester :)

**Comment by nicolaskruchten** [comment]
I should add that it's on our roadmap to bake this tool or something like it directly into Dash for development purposes, and I might not get around to upgrading this version before that happens... I'll happily accept pull-requests, though :)

**Comment by nicolaskruchten** [comment]
This code is now baked into Dash as of 0.42.0 (a few months ago) ... see https://dash.plot.ly/devtools
